/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab01_parte02_ejercicio.pkg01;

/**
 *
 * @author ADMIN
 */
public class Venatana extends javax.swing.JFrame {

    /**
     * Creates new form Venatana
     */
    public Venatana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Texto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ConvertidorMayusculas = new javax.swing.JButton();
        GenerarSaltoLinea = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ContenidoResultado = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        Texto.setBackground(new java.awt.Color(255, 255, 255));
        Texto.setForeground(new java.awt.Color(0, 0, 0));
        Texto.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Convertidor de miniscula a mayusculas - Generador de saltos de linea de un texto");

        ConvertidorMayusculas.setBackground(new java.awt.Color(102, 102, 102));
        ConvertidorMayusculas.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        ConvertidorMayusculas.setForeground(new java.awt.Color(255, 255, 255));
        ConvertidorMayusculas.setText("Convertir a mayusculas");
        ConvertidorMayusculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertidorMayusculasActionPerformed(evt);
            }
        });

        GenerarSaltoLinea.setBackground(new java.awt.Color(102, 102, 102));
        GenerarSaltoLinea.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        GenerarSaltoLinea.setForeground(new java.awt.Color(255, 255, 255));
        GenerarSaltoLinea.setText("Generar Saltos de Linea");
        GenerarSaltoLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarSaltoLineaActionPerformed(evt);
            }
        });

        ContenidoResultado.setBackground(new java.awt.Color(255, 255, 255));
        ContenidoResultado.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(ContenidoResultado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(ConvertidorMayusculas, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GenerarSaltoLinea)
                .addGap(158, 158, 158))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerarSaltoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConvertidorMayusculas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerarSaltoLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarSaltoLineaActionPerformed
        // TODO add your handling code here:
        
        ContenidoSaltoLinea p1=new ContenidoSaltoLinea();
        
        p1.setSize(800,340);
        p1.setLocation(0,0);
        
        ContenidoResultado.removeAll();
        
        String TextoEscrito = Texto.getText();
        
        String palabras[] = TextoEscrito.split(" ");
        for(int i=0;i<palabras.length;i++){
            p1.TextoArea.append(palabras[i]+"\n");
        }
        ContenidoResultado.add(p1);
        ContenidoResultado.revalidate();
        ContenidoResultado.repaint();
        
        
    }//GEN-LAST:event_GenerarSaltoLineaActionPerformed

    private void ConvertidorMayusculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertidorMayusculasActionPerformed
        // TODO add your handling code here:
        
        String Cadena=Texto.getText();
        
        String CadenaResultante=Cadena.toUpperCase();
        
        ContenidoResultado.removeAll();
        ContenidoResultado.revalidate();
        ContenidoResultado.repaint();
        
        ContenidoResultado.setText(CadenaResultante);
        
        
    }//GEN-LAST:event_ConvertidorMayusculasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venatana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venatana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venatana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venatana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venatana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane ContenidoResultado;
    private javax.swing.JButton ConvertidorMayusculas;
    private javax.swing.JButton GenerarSaltoLinea;
    private javax.swing.JTextField Texto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
